Oblig1WebApp/Oblig1WebApp/Controllers/BrukerController.cs
using BLL;
using Model;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Oblig1WebApp.Controllers
{
    public class BrukerController : Controller
    {
        private ILogikk _brukerBBL;

        public BrukerController()
        {
            _brukerBBL = new DBBLL();
        }

        public BrukerController(ILogikk stub)
        {
            _brukerBBL = stub;
        }

        public ActionResult Kontrollpanel()
        {
            if (Session["LoggetInn"] != null)
            {
                bool loggetInn = (bool)Session["LoggetInn"];
                if (loggetInn)
                {
                    return View();
                }
            }
            return RedirectToAction("LoggInn");
        }

        public ActionResult LoggInn()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoggInn(adminBruker innLogget)
        {
            //Sjekker om brukeren ble suksessfult innlogget
            if (_brukerBBL.bruker_i_db(innLogget))
            {
                //Brukernavn og passord er godtkjent
                Session["LoggetInn"] = true;
                Session["brukernavn"] = innLogget.brukernavn;
                ViewData["Innlogget"] = true;
                return View("Kontrollpanel");
            }
            else
            {
                //Brukernavn og passord ikke godkjent
                Session["LoggetInn"] = false;
                ViewData["Innlogget"] = false;
                ModelState.AddModelError("", "Innlogging feilet, feil brukernavn eller passord!");
                return View();
            }
        }

        public ActionResult RegistrerBruker()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegistrerBruker(adminBruker innBruker)
        {
            Session["nybruker"] = innBruker.brukernavn;

            if (innBruker.brukernavn.Length < 8)
            {
                ModelState.AddModelError("brukernavn", "Brukernavn er nødt til å bestå av minst 8 tegn");
            }
            else if (innBruker.passord.Length < 8)
            {
                ModelState.AddModelError("passord", "Passordet er nødt til å bestå av minst 8 tegn");
            }
            else
            {

                bool OK = _brukerBBL.lagreBruker(innBruker);

                if (OK)
                {
                    ViewData["RegistrertBruker"] = true;
                    ViewData["Brukernavntatt"] = false;
                    return View();
                }
                else
                {
                    if (_brukerBBL.bruker_i_db(innBruker))
                    {
                        ViewData["Brukernavntatt"] = true;
                    }
                    ViewData["RegistrertBruker"] = false;
                    return View();
                }
            }
            return View();
        }

        public ActionResult LoggUt()
        {
            Session["LoggetInn"] = false;
            TempData["LoggetUt"] = true;
            return RedirectToAction("LoggInn");
        }


        public ActionResult listBrukere()
        {
            List<adminBruker> alleBrukere = _brukerBBL.alleBrukere();
            return View(alleBrukere);
        }
    }
}

Oblig1WebApp/Oblig1WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - Vy</title>


    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <link rel="shortcut icon" href="~/Content/Images/vylogo.ico" />
   
    <script src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
            crossorigin="anonymous"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <a href="http://localhost:57882/Bestilling/Bestilling" class="navbar-left"><img src="~/Content/Images/vylogo-nav-justert.png"></a>
                @Html.ActionLink("Bestilling", "Bestilling", "Bestilling", new { area = "" }, new { @class = "navbar-brand" })
                <ul class="nav navbar-nav">
                    @{
                        if (Session["LoggetInn"] != null)
                        {
                            bool loggetInn = (bool)Session["LoggetInn"];
                            if (loggetInn)
                            {
                                @Html.ActionLink("Kontrollpanel", "Kontrollpanel", "Bruker", new { area = "" }, new { @class = "navbar-brand" })
                            }
                            else
                            {
                                @Html.ActionLink("Logg inn", "LoggInn", "Bruker", new { area = "" }, new { @class = "navbar-brand" })
                            }
                        }
                        else
                        {
                            @Html.ActionLink("Logg inn", "LoggInn", "Bruker", new { area = "" }, new { @class = "navbar-brand" })
                        }
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        @Scripts.Render("~/bundles/jqueryval")
        @RenderSection("scripts", false)
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vy</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>